"""Make a picture: generate a new image, or edit an existing one, and post it as an asset.

The complement to the assets tool's `view` (which lets a peer *see* an image):
these tools let a peer *make* and *change* one. Two tools, split by operation —
the discipline the capital's tool-building memory asks for (full surface → coverage
decided → split by operation → every option tested):

- `GenerateImageTool` (``generate_image``) — text → image. Asked to "draw a cat,"
  the agent calls this tool, ``gpt-image-2`` renders the pixels, and the result is
  uploaded as an Asset on the current timeline.
- `EditImageTool` (``edit_image``) — image(s) → image. Asked to "recolor this photo"
  or "composite these," the agent points at one or more source Assets (and an
  optional mask), the model edits them, and the result is uploaded the same way.

Both reach the web UI as a normal attachment that renders inline, exactly like a
human's.

Why function tools, not the provider built-in
----------------------------------------------
OpenAI's Responses API has a built-in ``image_generation`` tool that composes in
the model loop like ``web_search``. We deliberately do **not** use it here. The
generated bytes come back *inside the provider's response*, but posting them to
the timeline is platform I/O — and the provider is the *brain*, with no business
reaching the *body*'s SDK. Function tools keep that boundary clean: the tool (a
`PlatformTool`, so it holds the live SDK client) owns the upload, the provider
stays a pure text/tool-call adapter, and the capability works under **either**
provider — Chat Completions or Responses. It is the framework's core promise kept:
a new capability is one small tool class.

The image model is OpenAI's Images API, reached **through the ``openai`` SDK**
(``client.images.generate`` / ``client.images.edit``) — never hand-rolled HTTP, the same
vendor-SDK rule the model loop follows (issue #158). It shares the agent's ``AI_API_KEY``
(``gpt-5.4-mini`` reasons, ``gpt-image-2`` paints, one key). A non-OpenAI key simply gets a
model-readable error back, like any tool failure.

Coverage (audited to gpt-image-2's full surface)
-------------------------------------------------
Both tools expose the shared knobs gpt-image-2 honors: ``size``, ``quality``,
``background`` (opaque/auto — gpt-image-2 has **no** transparent), ``output_format``
(png/jpeg/webp), and ``output_compression`` (0–100, jpeg/webp only). The posted
Asset's filename extension follows ``output_format`` so its content-type does too
(the server infers the type from the name). ``n>1`` is deliberately skipped —
multiple-images-per-call is niche for a conversational agent (founder decision).
Enum/range constraints are documented in the schema and enforced by the API rather
than re-validated here, so this never drifts as the model's surface evolves.
"""

from __future__ import annotations

import os
from typing import Any

import httpx
from basecradle import BaseCradleError

from basecradle_harness._assets import _describe, _download, _upload
from basecradle_harness._exceptions import (
    ProviderConnectionError,
    ProviderError,
)
from basecradle_harness._media import (
    decode_image_payload,
    provider_error_message,
    slugify,
    uuid_list,
)
from basecradle_harness._observability import media_timer
from basecradle_harness._openai import require_openai_sdk, sdk_error_context
from basecradle_harness._platform import PlatformTool, explain

#: OpenAI's Images API root. Image generation/editing is an OpenAI service; this
#: changes only for a proxy, not to reach another vendor (the key is the OpenAI key).
DEFAULT_BASE_URL = "https://api.openai.com/v1"
#: The image model. ``gpt-image-2`` is what the live key carries; it returns the
#: rendered image as base64, no separate download step.
DEFAULT_MODEL = "gpt-image-2"
#: Default canvas. Square is universally supported; the model may pass another.
DEFAULT_SIZE = "1024x1024"
#: Generation/editing is slow next to a chat call — give it room before giving up.
#: A ``gpt-image-2`` ``quality: high`` edit was measured at ~133s live (issue #219), which
#: agents pick naturally for fidelity work, so the old 120s ceiling timed the common case
#: out. 300s clears the measured worst case with headroom for larger sizes; the constraint
#: is only that a normal ``quality: high`` request must not hit the ceiling.
DEFAULT_TIMEOUT = 300.0

#: ``output_format`` → filename extension. The Asset's content-type is inferred from
#: the filename (the SDK upload carries no explicit type), so the extension is how the
#: emitted format reaches the platform. png is the default when no format is named.
_FORMAT_EXTENSIONS = {"png": "png", "jpeg": "jpg", "webp": "webp"}

#: The shared coverage knobs, as JSON-schema properties, reused by both tools so the
#: model sees one consistent vocabulary for "how the image should come out."
_COVERAGE_PROPERTIES = {
    "size": {
        "type": "string",
        "description": (
            "Optional image dimensions, e.g. '1024x1024' (square), '1536x1024' "
            "(landscape), or '1024x1536' (portrait). Defaults to a square."
        ),
    },
    "quality": {
        "type": "string",
        "enum": ["low", "medium", "high", "auto"],
        "description": "Optional render quality. Higher is slower and costlier; 'auto' lets the model decide.",
    },
    "background": {
        "type": "string",
        "enum": ["opaque", "auto"],
        "description": (
            "Optional background. 'opaque' or 'auto' only — this model has no "
            "transparent background, so set this only if you specifically need opaque."
        ),
    },
    "output_format": {
        "type": "string",
        "enum": ["png", "jpeg", "webp"],
        "description": (
            "Optional output file format. Defaults to png. The posted file's extension "
            "and type follow this — use jpeg or webp for a smaller photo."
        ),
    },
    "output_compression": {
        "type": "integer",
        "description": (
            "Optional compression level 0-100 for jpeg/webp output only (lower = smaller "
            "file, lower quality). Has no effect on png and is dropped automatically there, "
            "so png output is never blocked by it."
        ),
    },
}


class _ImageTool(PlatformTool):
    """Shared base for the generate/edit image tools: key, coverage, request, upload.

    Both subclasses are `PlatformTool`s that hold the agent's ``AI_API_KEY`` and call the
    OpenAI Images API **through the ``openai`` SDK** (``client.images``), then upload the result
    through the bound platform SDK client. The only thing that differs is *which* SDK method
    they call and how they shape its arguments — generate takes a prompt, edit takes the source
    image bytes. Everything around that (key resolution, the shared coverage params, decoding
    the result, posting the Asset) lives here, once.

    Args:
        api_key: The OpenAI key for the Images API. Falls back to
            ``AI_API_KEY`` at call time, so constructing the tool needs no
            secret (a keyless construction just errors, readably, if used).
        base_url: The Images API root. Defaults to OpenAI.
        model: The image model. Defaults to ``gpt-image-2``.
        size: The default canvas when a call does not name one.
        timeout: Per-request timeout in seconds (generation/editing is slow).
    """

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        model: str = DEFAULT_MODEL,
        size: str = DEFAULT_SIZE,
        timeout: float = DEFAULT_TIMEOUT,
    ) -> None:
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._model = model
        self._default_size = size
        self._timeout = timeout

    # --- shared helpers -------------------------------------------------------

    def _key(self) -> str | None:
        """The OpenAI key: the explicit one, or the agent's provider key from env."""
        return self._api_key or os.environ.get("AI_API_KEY")

    def _client(self, key: str):
        """An ``openai`` SDK client for the Images API, plus the module (for error mapping).

        Built per call (image work is infrequent) and pointed at the configured base URL. The
        harness reaches the Images endpoint only through this SDK — no harness-owned HTTP.
        """
        openai = require_openai_sdk()
        client = openai.OpenAI(api_key=key, base_url=self._base_url, timeout=self._timeout)
        return openai, client

    def _coverage_params(
        self,
        *,
        size: str | None,
        quality: str | None,
        background: str | None,
        output_format: str | None,
        output_compression: int | None,
    ) -> dict[str, Any]:
        """The shared image params, omitting any the caller left unset.

        ``size`` always carries (the tool's default fills in); the rest are optional
        pass-through, so an unset knob lets the API choose its own default rather than
        the harness inventing one. Validation is the API's job (documented in the
        schema), which keeps this from drifting as the model's surface changes.
        """
        params: dict[str, Any] = {"size": size or self._default_size}
        if quality:
            params["quality"] = quality
        if background:
            params["background"] = background
        if output_format:
            params["output_format"] = output_format
        # ``output_compression`` is jpeg/webp-only: OpenAI hard-400s it on png
        # ("Compression less than 100 is not supported for PNG output format"), and
        # png is the default when no format is named. The model fills the schema field
        # in freely, so dropping it for png here — where the docs already say it's
        # ignored — turns a live footgun into a no-op rather than trusting the model to
        # avoid it. (Capital live-verify, #140.)
        fmt = (output_format or "png").lower()
        if output_compression is not None and fmt != "png":
            params["output_compression"] = output_compression
        return params

    def _decode(self, response: object) -> bytes:
        """The image bytes from an SDK Images response (``b64_json``, or a ``url`` to fetch)."""
        return decode_image_payload(
            response.model_dump(), download=_download, subject="the image API"
        )

    def _post_asset(
        self,
        timeline: str,
        image_bytes: bytes,
        name: str,
        description: str,
        verb: str,
    ) -> str:
        """Upload the produced bytes as an Asset and report it for the model to read.

        `verb` is the past-tense action ("Generated and posted" / "Edited and posted"),
        so each tool's report reads naturally while the upload-and-describe lives once.
        """
        asset = _upload(self.context.client, timeline, image_bytes, name, description)
        self.acted("asset", asset.content.uuid)  # an image on a timeline is a visible act (#293)
        return f"{verb} {name!r} ({len(image_bytes)} bytes). {_describe(asset)}"


class GenerateImageTool(_ImageTool):
    """Generate an image from a prompt and post it as an asset on the timeline.

    A `PlatformTool`: the hosting agent (`TimelineAgent`/`WakeAgent`) binds the SDK
    client and current-timeline uuid before the loop, exactly like the assets tool.
    """

    name = "generate_image"
    description = (
        "Create an image from a text prompt and post it as a file on the timeline, "
        "the way a peer shares a picture they made. Describe what to draw in 'prompt'; "
        "the image is generated and uploaded as an asset (it renders inline for humans). "
        "Choose 'output_format' (png/jpeg/webp), 'size', 'quality', and 'background' to "
        "control how it comes out. To change an image that already exists, use 'edit_image' "
        "instead. Optionally set a 'filename', a 'description', or a 'timeline' uuid to post "
        "somewhere other than the current one."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {
                "type": "string",
                "description": "What to draw — describe the image you want generated.",
            },
            **_COVERAGE_PROPERTIES,
            "filename": {
                "type": "string",
                "description": "Optional filename for the posted image, e.g. 'sunset.png'.",
            },
            "description": {
                "type": "string",
                "description": "Optional human-readable description of the posted image.",
            },
            "timeline": {
                "type": "string",
                "description": (
                    "Optional timeline uuid to post to instead of the current one. "
                    "Omit to use the timeline you are engaged on."
                ),
            },
        },
        "required": ["prompt"],
    }

    def run(
        self,
        prompt: str,
        size: str | None = None,
        quality: str | None = None,
        background: str | None = None,
        output_format: str | None = None,
        output_compression: int | None = None,
        filename: str | None = None,
        description: str | None = None,
        timeline: str | None = None,
    ) -> str:
        """Generate the image, upload it, and report the new asset for the model to read."""
        if not prompt or not prompt.strip():
            return "Error: 'generate_image' needs a 'prompt' describing what to draw."
        key = self._key()
        if not key:
            return (
                "Error: no API key for image generation. Set AI_API_KEY "
                "(or pass api_key= to GenerateImageTool)."
            )

        coverage = self._coverage_params(
            size=size,
            quality=quality,
            background=background,
            output_format=output_format,
            output_compression=output_compression,
        )
        try:
            openai, client = self._client(key)
            with (
                media_timer(provider="openai", kind="image.generate", model=self._model),
                sdk_error_context(openai),
            ):
                response = client.images.generate(model=self._model, prompt=prompt, n=1, **coverage)
            image_bytes = self._decode(response)
        except ProviderConnectionError as exc:
            return f"Error generating image: could not reach the image API: {exc}"
        except ProviderError as exc:
            return f"Error generating image: {_provider_message(exc)}"

        target = timeline or self.context.timeline
        name = _image_filename(filename, prompt, output_format)
        return self._post_asset(
            target,
            image_bytes,
            name,
            description or f"Generated image: {prompt}",
            "Generated and posted",
        )


class EditImageTool(_ImageTool):
    """Edit one or more existing image assets with a prompt and post the result.

    Mirrors `GenerateImageTool`, but calls OpenAI's ``/v1/images/edits`` — the source
    image is sent as **bytes, not a URL** (the endpoint rejects URLs). So the tool
    resolves each source Asset by uuid, downloads its bytes through the bound SDK
    client / its signed blob URL, and uploads those bytes as the multipart body. An
    optional ``mask`` Asset (its alpha channel marks the region to change) is resolved
    the same way. The edited result is posted as a new Asset, exactly like generate.

    Multiple source uuids composite several images into one edit; a single uuid is the
    common recolor/inpaint case.
    """

    name = "edit_image"
    description = (
        "Edit an image that already exists on the timeline and post the result as a new "
        "file, the way a peer marks up or restyles a picture. Give one or more source "
        "asset uuids in 'image' (find them with the assets tool's 'list') and describe the "
        "change in 'prompt' (e.g. 'recolor the car red', or composite several sources). "
        "Optionally pass a 'mask' asset uuid — a same-size image whose transparent area "
        "marks the region to change, leaving the rest untouched. Choose 'output_format' "
        "(png/jpeg/webp), 'size', 'quality', and 'background' as with generate_image. To "
        "make a brand-new image from text instead, use 'generate_image'."
    )
    parameters = {
        "type": "object",
        "properties": {
            "image": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "One or more source image asset uuids to edit. Get them from the "
                    "assets tool's 'list'. Pass several to composite them into one image."
                ),
            },
            "prompt": {
                "type": "string",
                "description": "How to change the image — describe the edit you want.",
            },
            "mask": {
                "type": "string",
                "description": (
                    "Optional mask asset uuid: a same-size image whose transparent "
                    "(alpha) area marks exactly the region to change. Omit to let the "
                    "model decide where to edit."
                ),
            },
            **_COVERAGE_PROPERTIES,
            "filename": {
                "type": "string",
                "description": "Optional filename for the posted image, e.g. 'recolored.png'.",
            },
            "description": {
                "type": "string",
                "description": "Optional human-readable description of the posted image.",
            },
            "timeline": {
                "type": "string",
                "description": (
                    "Optional timeline uuid to post to instead of the current one. "
                    "Omit to use the timeline you are engaged on."
                ),
            },
        },
        "required": ["image", "prompt"],
    }

    def run(
        self,
        image: list[str] | str | None = None,
        prompt: str | None = None,
        mask: str | None = None,
        size: str | None = None,
        quality: str | None = None,
        background: str | None = None,
        output_format: str | None = None,
        output_compression: int | None = None,
        filename: str | None = None,
        description: str | None = None,
        timeline: str | None = None,
    ) -> str:
        """Edit the source image(s), upload the result, and report the new asset."""
        if not prompt or not prompt.strip():
            return "Error: 'edit_image' needs a 'prompt' describing the change to make."
        uuids = uuid_list(image)
        if not uuids:
            return (
                "Error: 'edit_image' needs at least one source 'image' asset uuid. "
                "Use the assets tool's 'list' to find one."
            )
        key = self._key()
        if not key:
            return (
                "Error: no API key for image editing. Set AI_API_KEY "
                "(or pass api_key= to EditImageTool)."
            )

        try:
            sources = [self._source_part(uuid) for uuid in uuids]
            mask_part = self._source_part(mask) if mask else None
        except _SourceError as exc:
            return str(exc)

        coverage = self._coverage_params(
            size=size,
            quality=quality,
            background=background,
            output_format=output_format,
            output_compression=output_compression,
        )
        # The SDK's ``image`` takes one file or a list; ``mask`` is a single file. Both are
        # ``(filename, bytes, content_type)`` tuples — the bytes, not a URL (the edit endpoint
        # rejects URLs), which is why each source is downloaded inline above.
        extra: dict[str, Any] = {"mask": mask_part} if mask_part is not None else {}
        try:
            openai, client = self._client(key)
            with (
                media_timer(provider="openai", kind="image.edit", model=self._model),
                sdk_error_context(openai),
            ):
                response = client.images.edit(
                    model=self._model, image=sources, prompt=prompt, n=1, **extra, **coverage
                )
            image_bytes = self._decode(response)
        except ProviderConnectionError as exc:
            return f"Error editing image: could not reach the image API: {exc}"
        except ProviderError as exc:
            return f"Error editing image: {_provider_message(exc)}"

        target = timeline or self.context.timeline
        name = _image_filename(filename, prompt, output_format)
        return self._post_asset(
            target, image_bytes, name, description or f"Edited image: {prompt}", "Edited and posted"
        )

    def _source_part(self, uuid: str) -> tuple[str, bytes, str]:
        """Resolve a source/mask Asset by uuid to an SDK file tuple (bytes, not a URL).

        The Images edit endpoint rejects URLs, so the bytes must be downloaded and sent
        inline as a ``(filename, bytes, content_type)`` file the SDK uploads. A bad uuid (or a
        download failure) raises `_SourceError`, whose message the caller relays to the model.
        """
        try:
            asset = self.context.client.assets.get(uuid)
            file = asset.content.file
            data = _download(file.url)
        except BaseCradleError as error:
            raise _SourceError(
                f"Error editing image: couldn't read asset {uuid!r}: {explain(error)}"
            )
        except httpx.HTTPError as exc:
            raise _SourceError(f"Error editing image: couldn't download asset {uuid!r}: {exc}")
        return (file.filename, data, file.content_type)


class _SourceError(Exception):
    """A model-readable failure resolving a source/mask asset for an edit."""


def _provider_message(exc: ProviderError) -> str:
    """A legible relay of an Images-API failure, for the model to pass to the user.

    Delegates to the shared `provider_error_message` (the same relay the grok media tools use):
    a `ProviderAPIError`'s own ``str`` is only the generic "Provider returned HTTP 400" — the
    real cause lives in its body under ``error.message`` (e.g. "Compression less than 100 is
    not supported for PNG output format"). Surface that so the AI relays the true cause, not an
    opaque status — Principle 5 (capital live verify, #140).
    """
    return provider_error_message(exc, "the image API")


def _image_filename(filename: str | None, fallback_text: str, output_format: str | None) -> str:
    """A safe filename whose extension follows ``output_format`` (png by default).

    The Asset's content-type is inferred from its filename on upload, so the extension
    is how the emitted format reaches the platform — this is the fix for the old
    hard-coded ``.png``. Assets are addressed by their own uuid, so two images sharing
    a filename never collide — a readable name is for humans, not uniqueness.
    """
    ext = _FORMAT_EXTENSIONS.get((output_format or "png").lower(), "png")
    base = filename.rsplit(".", 1)[0] if filename else fallback_text
    return f"{slugify(base) or 'image'}.{ext}"
