"""Make a picture: generate an image and post it as an asset on the timeline.

The complement to the assets tool's `view` (which lets a peer *see* an image):
`GenerateImageTool` lets a peer *make* one. Asked to "draw a cat," the agent calls
this tool, an image model (``gpt-image-2`` by default) renders the pixels, and the
result is uploaded as an Asset on the current timeline — where the web UI renders
it inline, the same as any human's attachment.

Why a function tool, not a built-in
------------------------------------
OpenAI's Responses API has a built-in ``image_generation`` tool that composes in
the model loop like ``web_search``. We deliberately do **not** use it here. The
generated bytes come back *inside the provider's response*, but posting them to
the timeline is platform I/O — and the provider is the *brain*, with no business
reaching the *body*'s SDK. A function tool keeps that boundary clean: the tool
(a `PlatformTool`, so it holds the live SDK client) owns the upload, the provider
stays a pure text/tool-call adapter, and the capability works under **either**
provider — Chat Completions or Responses — not only the Responses path. It is the
framework's core promise kept: a new capability is one small tool class.

The image model is OpenAI's Images API (``/v1/images/generations``); it shares the
agent's ``AI_PROVIDER_API_KEY`` (``gpt-5.4-mini`` reasons, ``gpt-image-2`` paints,
one key). A non-OpenAI key simply gets a model-readable error back, like any tool
failure.
"""

from __future__ import annotations

import base64
import os
import re
from typing import Any

import httpx

from basecradle_harness._assets import _describe, _upload
from basecradle_harness._exceptions import ProviderConnectionError, ProviderError
from basecradle_harness._http import raise_for_status
from basecradle_harness._platform import PlatformTool

#: OpenAI's Images API root. Image generation is an OpenAI service; this changes
#: only for a proxy, not to reach another vendor (the key is the OpenAI key).
DEFAULT_BASE_URL = "https://api.openai.com/v1"
#: The image model. ``gpt-image-2`` is what the live key carries; it returns the
#: rendered image as base64, no separate download step.
DEFAULT_MODEL = "gpt-image-2"
#: Default canvas. Square is universally supported; the model may pass another.
DEFAULT_SIZE = "1024x1024"
#: Generation is slow next to a chat call — give it room before giving up.
DEFAULT_TIMEOUT = 120.0


class GenerateImageTool(PlatformTool):
    """Generate an image from a prompt and post it as an asset on the timeline.

    A `PlatformTool`: it uploads through the bound SDK client, so the hosting agent
    (`TimelineAgent`/`WakeAgent`) binds it before the loop, exactly like the assets
    tool. The image model's key is the agent's ``AI_PROVIDER_API_KEY`` unless an
    explicit `api_key` is passed.

    Args:
        api_key: The OpenAI key for the Images API. Falls back to
            ``AI_PROVIDER_API_KEY`` at call time, so constructing the tool needs no
            secret (a keyless construction just errors, readably, if used).
        base_url: The Images API root. Defaults to OpenAI.
        model: The image model. Defaults to ``gpt-image-2``.
        size: The default canvas when a call does not name one.
        timeout: Per-request timeout in seconds (generation is slow).
    """

    name = "generate_image"
    description = (
        "Create an image from a text prompt and post it as a file on the timeline, "
        "the way a peer shares a picture they made. Describe what to draw in 'prompt'; "
        "the image is generated and uploaded as an asset (it renders inline for "
        "humans). Optionally set 'size', a 'filename', a 'description', or a 'timeline' "
        "uuid to post somewhere other than the current one."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {
                "type": "string",
                "description": "What to draw — describe the image you want generated.",
            },
            "size": {
                "type": "string",
                "description": (
                    "Optional image dimensions, e.g. '1024x1024' (square), '1536x1024' "
                    "(landscape), or '1024x1536' (portrait). Defaults to a square."
                ),
            },
            "filename": {
                "type": "string",
                "description": "Optional filename for the posted image, e.g. 'sunset.png'.",
            },
            "description": {
                "type": "string",
                "description": "Optional human-readable description of the posted image.",
            },
            "timeline": {
                "type": "string",
                "description": (
                    "Optional timeline uuid to post to instead of the current one. "
                    "Omit to use the timeline you are engaged on."
                ),
            },
        },
        "required": ["prompt"],
    }

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        model: str = DEFAULT_MODEL,
        size: str = DEFAULT_SIZE,
        timeout: float = DEFAULT_TIMEOUT,
    ) -> None:
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._model = model
        self._default_size = size
        self._timeout = timeout

    def run(
        self,
        prompt: str,
        size: str | None = None,
        filename: str | None = None,
        description: str | None = None,
        timeline: str | None = None,
    ) -> str:
        """Generate the image, upload it, and report the new asset for the model to read."""
        if not prompt or not prompt.strip():
            return "Error: 'generate_image' needs a 'prompt' describing what to draw."
        key = self._api_key or os.environ.get("AI_PROVIDER_API_KEY")
        if not key:
            return (
                "Error: no API key for image generation. Set AI_PROVIDER_API_KEY "
                "(or pass api_key= to GenerateImageTool)."
            )

        try:
            image_bytes = self._generate(prompt, size or self._default_size, key)
        except ProviderConnectionError as exc:
            return f"Error generating image: could not reach the image API: {exc}"
        except ProviderError as exc:
            return f"Error generating image: {exc}"

        target = timeline or self.context.timeline
        name = _image_filename(filename, prompt)
        asset = _upload(
            self.context.client,
            target,
            image_bytes,
            name,
            description or f"Generated image: {prompt}",
        )
        return f"Generated and posted {name!r} ({len(image_bytes)} bytes). {_describe(asset)}"

    def _generate(self, prompt: str, size: str, key: str) -> bytes:
        """Render the image and return its bytes (the Images API returns base64).

        Failures surface as the same typed `ProviderError`s the model-provider
        adapters raise — `run` catches them and relays the message to the model.
        """
        payload: dict[str, Any] = {
            "model": self._model,
            "prompt": prompt,
            "size": size,
            "n": 1,
        }
        try:
            with httpx.Client(
                headers={"Authorization": f"Bearer {key}"}, timeout=self._timeout
            ) as client:
                response = client.post(f"{self._base_url}/images/generations", json=payload)
        except httpx.RequestError as exc:
            raise ProviderConnectionError(str(exc)) from exc
        if response.status_code >= 400:
            raise_for_status(response)  # raises a typed ProviderAPIError carrying the body
        return _decode_image(response.json())


def _decode_image(body: dict[str, Any]) -> bytes:
    """Pull the base64 image out of an Images API response and decode it to bytes."""
    items = body.get("data") or []
    item = items[0] if items else None
    encoded = item.get("b64_json") if isinstance(item, dict) else None
    if not encoded:
        raise ProviderError("the image API returned no image data.")
    try:
        return base64.b64decode(encoded)
    except (ValueError, TypeError) as exc:
        raise ProviderError(f"the image API returned undecodable data: {exc}") from exc


def _image_filename(filename: str | None, prompt: str) -> str:
    """A safe ``.png`` filename: the caller's, or a slug derived from the prompt.

    Assets are addressed by their own uuid on the platform, so two images sharing a
    filename never collide — a readable name is for humans, not uniqueness.
    """
    if filename:
        stem = filename.rsplit(".", 1)[0]
        return f"{_slug(stem) or 'image'}.png"
    return f"{_slug(prompt) or 'image'}.png"


def _slug(text: str) -> str:
    """A short, filename-safe slug: lowercased words joined by hyphens, capped."""
    words = re.findall(r"[a-z0-9]+", text.lower())
    return "-".join(words)[:48].strip("-")
